version: "3.8"
name: app-compose-prod

services:
  scylla-init:
    image: scylladb/scylla:5.4
    container_name: zalo_scylla_init
    volumes:
      - ./infra/scylla:/infra/scylla
    environment:
      - SCYLLA_CONTACT_POINTS=${SCYLLA_CONTACT_POINTS:-scylla}
      - SCYLLA_LOCAL_DATACENTER=${SCYLLA_LOCAL_DATACENTER:-datacenter1}
      - SCYLLA_KEYSPACE=${SCYLLA_KEYSPACE:-chat}

    entrypoint: ["/bin/bash", "-c"]

    command: >
      "
      echo 'Waiting for ScyllaDB at $${SCYLLA_CONTACT_POINTS} to be ready...';
      while ! cqlsh $${SCYLLA_CONTACT_POINTS} 9042 -e 'DESCRIBE CLUSTER'; do
        echo 'ScyllaDB not ready yet... sleeping';
        sleep 5;
      done;
      echo 'ScyllaDB is ready! Initializing schema...';
      cqlsh $${SCYLLA_CONTACT_POINTS} 9042 -f /infra/scylla/schema.cql;
      echo 'Schema initialized.';
      "
    depends_on:
      scylla:
        condition: service_healthy
    networks:
      - zalo_network
    restart: "no"

  scylla:
    image: scylladb/scylla:5.4
    container_name: zalo_scylla
    command: ["--smp", "1", "--memory", "512M", "--overprovisioned", "1"]
    volumes:
      - scylla_data:/var/lib/scylla
    networks:
      - zalo_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe cluster"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
  
  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    container_name: zalo_migration
    environment:
      NODE_ENV: production
      # Database - AWS RDS
      DB_HOST: database-1.cda2o0ikkgnf.ap-southeast-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_USERNAME: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_NAME: ${POSTGRES_DB:-postgres}
    networks:
      - zalo_network
    restart: "no"
    profiles:
      - migration

volumes:
  scylla_data:
    driver: local

networks:
  zalo_network:
    external: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
