export const KafkaTopics = {
  ChatMessageSend: 'chat.message.send',
  ChatMessageCreated: 'chat.message.created',
  ChatMessageEdit: 'chat.message.edit',
  ChatMessageUpdated: 'chat.message.updated',
  ChatMessageDelete: 'chat.message.delete',
  ChatMessageRecall: 'chat.message.delete',
  ChatMessageDeleted: 'chat.message.deleted',
  ChatMessageRecalled: 'chat.message.deleted',
  ChatMessageForward: 'chat.message.forward',
  ChatReactionAdd: 'chat.reaction.add',
  ChatReactionAdded: 'chat.reaction.added',
  ChatReactionRemove: 'chat.reaction.remove',
  ChatReactionRemoved: 'chat.reaction.removed',
  ChatMessagePinned: 'chat.message.pinned',
  ChatMessageUnpinned: 'chat.message.unpinned',
  ChatSystemMessageCreated: 'chat.system-message.created',
  ChatInviteMessageCreated: 'chat.invite-message.created',
  ChatInviteMessageUpdated: 'chat.invite-message.updated',

  CallStart: 'call.start',
  CallStarted: 'call.started',
  CallSignalSend: 'call.signal.send',
  CallSignalForwarded: 'call.signal.forwarded',
  CallAccept: 'call.accept',
  CallAccepted: 'call.accepted',
  CallReject: 'call.reject',
  CallRejected: 'call.rejected',
  CallEnd: 'call.end',
  CallEnded: 'call.ended',
  CallStateRequest: 'call.state.request',
  CallStateUpdated: 'call.state.updated',
  CallLeave: 'call.leave',
  CallLeft: 'call.left',
  CallTimeout: 'call.timeout',
  CallTimedOut: 'call.timed-out',

  ConversationCreated: 'conversation.created',
  ConversationUpdated: 'conversation.updated',
  ConversationSettingsUpdated: 'conversation.settings.updated',
  ConversationDisbanded: 'conversation.disbanded',
  ConversationMemberAdded: 'conversation.member.added',
  ConversationMemberRemoved: 'conversation.member.removed',
  ConversationMemberRoleUpdated: 'conversation.member.role.updated',

  GroupInviteSent: 'group.invite.sent',
  GroupInviteAccepted: 'group.invite.accepted',
  GroupInviteRejected: 'group.invite.rejected',
  GroupInviteCancelled: 'group.invite.cancelled',
  GroupInviteExpired: 'group.invite.expired',

  ConversationPollCreated: 'conversation.poll.created',
  ConversationPollEdited: 'conversation.poll.edited',
  ConversationPollClosed: 'conversation.poll.closed',
  ConversationPollVoteCast: 'conversation.poll.vote.cast',
  ConversationPollVoteRetracted: 'conversation.poll.vote.retracted',
  ConversationPollOptionAdded: 'conversation.poll.option.added',
  ConversationPollOptionRemoved: 'conversation.poll.option.removed',
  ChatPollMessageCreated: 'chat.poll-message.created',
  ChatPollMessageUpdated: 'chat.poll-message.updated',

  PresenceConnect: 'presence.connect',
  PresenceDisconnect: 'presence.disconnect',
  PresenceHeartbeat: 'presence.heartbeat',
  PresenceUpdated: 'presence.updated',

  MediaUploadRequested: 'media.upload.requested',
  MediaUploaded: 'media.uploaded',
  MediaThumbnailGenerated: 'media.thumbnail.generated',

  NotificationRequested: 'notification.requested',
  NotificationBatch: 'notification.batch',
  NotificationSent: 'notification.sent',
  NotificationFailed: 'notification.failed',

  AuthQrConfirmed: 'auth.qr.confirmed',
  AuthQrRejected: 'auth.qr.rejected',

  SendFriendRequest: 'friend.request.send',
  RespondFriendRequest: 'friend.request.respond',
  CancelFriendRequest: 'friend.request.cancelled',
  FriendRemoved: 'friend.removed',
  ConversationPinned: 'conversation.pinned',
  ConversationUnpinned: 'conversation.unpinned',

  AiModerationRequest: 'ai.moderation.request',
  AiModerationResult: 'ai.moderation.result',
  AiModerationEnforcement: 'ai.moderation.enforcement',
  AiSmartReplyRequest: 'ai.smart-reply.request',
  AiSmartReplyResult: 'ai.smart-reply.result',
  AiSummaryRequest: 'ai.summary.request',
  AiSummaryResult: 'ai.summary.result',
  AiTranslateRequest: 'ai.translate.request',
  AiTranslateResult: 'ai.translate.result',
  AiDocumentUpload: 'ai.document.upload',
  AiDocumentProcessed: 'ai.document.processed',
  AiDocumentQuery: 'ai.document.query',
  AiDocumentQueryResult: 'ai.document.query.result',
  AiStreamChunk: 'ai.stream.chunk',
  AiStreamComplete: 'ai.stream.complete',
  AiEntityDetectionRequest: 'ai.entity.detection.request',
  AiEntityDetectionResult: 'ai.entity.detection.result',
  AiEntityInfoRequest: 'ai.entity.info.request',
  AiEntityInfoResult: 'ai.entity.info.result',
  AiZaiChatRequest: 'ai.zai.chat.request',
  ChatAiMessage: 'chat.ai.message',
} as const;

export type KafkaTopic = (typeof KafkaTopics)[keyof typeof KafkaTopics];
