import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsNotEmpty,
  IsUUID,
  ValidateNested,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class ForwardTargetDto {
  @ApiProperty({ description: 'Target message ID (generated by BFF)' })
  @IsUUID()
  @IsNotEmpty()
  message_id!: string;

  @ApiProperty({ description: 'Target conversation ID' })
  @IsUUID()
  @IsNotEmpty()
  conversation_id!: string;
}

export class ForwardMessageDto {
  @ApiProperty({ description: 'Forward operation idempotency key' })
  @IsUUID()
  @IsNotEmpty()
  forward_id!: string;

  @ApiProperty({ description: 'Source message ID to forward' })
  @IsUUID()
  @IsNotEmpty()
  source_message_id!: string;

  @ApiProperty({ type: [ForwardTargetDto], description: 'Forward targets' })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(20)
  @ValidateNested({ each: true })
  @Type(() => ForwardTargetDto)
  targets!: ForwardTargetDto[];
}

export class ForwardTargetResultDto {
  @ApiProperty({ description: 'Target message ID' })
  message_id!: string;

  @ApiProperty({ description: 'Target conversation ID' })
  conversation_id!: string;

  @ApiProperty({ enum: ['accepted', 'rejected'] })
  status!: 'accepted' | 'rejected';

  @ApiPropertyOptional({ description: 'Rejection reason if any' })
  reason?: string;
}

export class ForwardMessageResultDto {
  @ApiProperty({ description: 'Forward operation idempotency key' })
  forward_id!: string;

  @ApiProperty({ type: [ForwardTargetResultDto] })
  results!: ForwardTargetResultDto[];
}
