/**
 * Error codes for the application
 * Format: DOMAIN_ACTION_ERROR
 */
export enum ErrorCode {
  // ============== COMMON ==============
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  BAD_REQUEST = 'BAD_REQUEST',
  CONFLICT = 'CONFLICT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // ============== AUTH ==============
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  AUTH_OTP_INVALID = 'AUTH_OTP_INVALID',
  AUTH_TOO_MANY_ATTEMPTS = 'AUTH_TOO_MANY_ATTEMPTS',

  // ============== USER ==============
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_PHONE_ALREADY_EXISTS = 'USER_PHONE_ALREADY_EXISTS',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_INVALID_PASSWORD = 'USER_INVALID_PASSWORD',
  USER_CANNOT_UPDATE = 'USER_CANNOT_UPDATE',

  // ============== FRIEND ==============
  FRIEND_REQUEST_NOT_FOUND = 'FRIEND_REQUEST_NOT_FOUND',
  FRIEND_REQUEST_ALREADY_EXISTS = 'FRIEND_REQUEST_ALREADY_EXISTS',
  FRIEND_ALREADY_FRIENDS = 'FRIEND_ALREADY_FRIENDS',
  FRIEND_CANNOT_ADD_SELF = 'FRIEND_CANNOT_ADD_SELF',
  FRIEND_USER_BLOCKED = 'FRIEND_USER_BLOCKED',
  FRIEND_NOT_FOUND = 'FRIEND_NOT_FOUND',

  // ============== CONVERSATION ==============
  CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND',
  CONVERSATION_MEMBER_NOT_FOUND = 'CONVERSATION_MEMBER_NOT_FOUND',
  CONVERSATION_PERMISSION_DENIED = 'CONVERSATION_PERMISSION_DENIED',
  CONVERSATION_ALREADY_MEMBER = 'CONVERSATION_ALREADY_MEMBER',
  CONVERSATION_NOT_MEMBER = 'CONVERSATION_NOT_MEMBER',
  CONVERSATION_CANNOT_LEAVE = 'CONVERSATION_CANNOT_LEAVE',
  CONVERSATION_INVALID_TYPE = 'CONVERSATION_INVALID_TYPE',
  GROUP_INVITE_NOT_FOUND = 'GROUP_INVITE_NOT_FOUND',
  GROUP_INVITE_ALREADY_EXISTS = 'GROUP_INVITE_ALREADY_EXISTS',
  GROUP_INVITE_EXPIRED = 'GROUP_INVITE_EXPIRED',
  GROUP_INVITE_INVALID_STATUS = 'GROUP_INVITE_INVALID_STATUS',
  OWNER_TRANSFER_REQUIRED = 'OWNER_TRANSFER_REQUIRED',

  // ============== MESSAGE ==============
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  MESSAGE_PERMISSION_DENIED = 'MESSAGE_PERMISSION_DENIED',
  MESSAGE_EDIT_WINDOW_EXPIRED = 'MESSAGE_EDIT_WINDOW_EXPIRED',
  MESSAGE_ALREADY_DELETED = 'MESSAGE_ALREADY_DELETED',

  // ============== POST ==============
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  POST_PERMISSION_DENIED = 'POST_PERMISSION_DENIED',
  POST_ALREADY_DELETED = 'POST_ALREADY_DELETED',
  POST_CONTENT_REQUIRED = 'POST_CONTENT_REQUIRED',

  // ============== COMMENT ==============
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_PERMISSION_DENIED = 'COMMENT_PERMISSION_DENIED',
  COMMENT_ALREADY_DELETED = 'COMMENT_ALREADY_DELETED',

  // ============== MEDIA ==============
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  MEDIA_UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',
  MEDIA_INVALID_TYPE = 'MEDIA_INVALID_TYPE',
  MEDIA_SIZE_EXCEEDED = 'MEDIA_SIZE_EXCEEDED',
  MEDIA_PERMISSION_DENIED = 'MEDIA_PERMISSION_DENIED',

  // ============== NOTIFICATION ==============
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_DEVICE_NOT_FOUND = 'NOTIFICATION_DEVICE_NOT_FOUND',
  NOTIFICATION_SEND_FAILED = 'NOTIFICATION_SEND_FAILED',

  // ============== QR LOGIN ==============
  QR_SESSION_NOT_FOUND = 'QR_SESSION_NOT_FOUND',
  QR_SESSION_EXPIRED = 'QR_SESSION_EXPIRED',
  QR_SESSION_ALREADY_PROCESSED = 'QR_SESSION_ALREADY_PROCESSED',
  QR_SESSION_INVALID = 'QR_SESSION_INVALID',

  // ============== POLL ==============
  POLL_NOT_FOUND = 'POLL_NOT_FOUND',
  POLL_CLOSED = 'POLL_CLOSED',
  POLL_EXPIRED = 'POLL_EXPIRED',
  POLL_NOT_GROUP_CONVERSATION = 'POLL_NOT_GROUP_CONVERSATION',
  POLL_INVALID_OPTION = 'POLL_INVALID_OPTION',
  POLL_ADD_OPTION_NOT_ALLOWED = 'POLL_ADD_OPTION_NOT_ALLOWED',
  POLL_OPTION_LIMIT_REACHED = 'POLL_OPTION_LIMIT_REACHED',
  POLL_MIN_OPTIONS_REQUIRED = 'POLL_MIN_OPTIONS_REQUIRED',
  POLL_SINGLE_CHOICE_VIOLATION = 'POLL_SINGLE_CHOICE_VIOLATION',
  POLL_DUPLICATE_OPTION_LABEL = 'POLL_DUPLICATE_OPTION_LABEL',
  POLL_PERMISSION_DENIED = 'POLL_PERMISSION_DENIED',
  POLL_CANNOT_EDIT_MULTIPLE_WITH_VOTES = 'POLL_CANNOT_EDIT_MULTIPLE_WITH_VOTES',
  POLL_CANNOT_EDIT_OPTION_WITH_VOTES = 'POLL_CANNOT_EDIT_OPTION_WITH_VOTES',
  POLL_EXPIRES_AT_IN_PAST = 'POLL_EXPIRES_AT_IN_PAST',
  POLL_NO_EDIT_FIELDS = 'POLL_NO_EDIT_FIELDS',
}
